# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Vibrant Shadows"
license = "MIT"
licenselink = "https://github.com/Softorage/HugoTheme-VibrantShadows/blob/master/LICENSE"
description = "An insanely customizable, extremely lightweight and ridiculously fast 'Blog Theme' for Hugo, with mobile support and a lot more."
homepage = "https://github.com/Softorage/HugoTheme-VibrantShadows/"
tags = ["blog", "website", "professional"]
features = ["lightweight", "fast", "elegant", "customizable", "clean", "seo optimized", "cookie consent"]
min_version = "0.75.1"

[author]
  name = "Softorage"
  homepage = "https://softorage.com"

